# Site settings
title: David S. Zou
email: davidzsy20@yahoo.com
url: https://davidzsy20.github.io
description: "I build everything."
keywords: "Music saves my vibe."
skills: "Full-Stack Software Engineer, DJ"
meta_author: David Zou

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. DJ.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: twitter.com/Davidzsy20?lang=en
  - title: facebook
    url: https://www.facebook.com/david.zou.144
  - title: stack-overflow
    url: http://bit.ly/2iXGIef
  - title: github
    url: http://github.com/davidzsy20

# Postal address (add as many lines as necessary)
address:
  - line: 4310 Crescent Street
  - line: Long Is City, NY 11101

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - vendor
